spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: aws-secretsmanager:secret/meetup
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

kakao:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URL}

jwt:
  secret: ${JWT_SECRET}
  access-token-expired-time: 3600000

cloud:
  aws:
    s3:
      bucket: ddoba
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

default-profile:
  image:${DEFAULT_PROFILE_IMAGE}